#Category

# GET http://localhost:5000/api/categories
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ItCU0LzQuNGC0YDQuNC5Iiwicm9sZSI6ImxleHVzX2RyaXZlciIsIm5iZiI6MTU4NTU1ODYyOSwiZXhwIjoxNTg1NTYwNDI5LCJpYXQiOjE1ODU1NTg2Mjl9.W7H45XK12zwoyrWjEPT2BkeIk5HdmXbwXeR6XwNzUJs

# POST http://localhost:5000/api/categories
# Content-Type: application/json
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ItCb0Y7QtNC80LjQu9CwIiwicm9sZSI6ImNvcm9sbGFfZHJpdmVyIiwibmJmIjoxNTg1NDQyMDkyLCJleHAiOjE1ODU0NDM4OTIsImlhdCI6MTU4NTQ0MjA5Mn0.jcJBe4k3Q6XJBc4_LgGse1b_aSx3oT3NbMIAGq3wV18
# {
#     "Name": "Printer"
# }

# PUT http://localhost:5000/api/categories/1
# Content-Type: application/json
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ItCb0Y7QtNC80LjQu9CwIiwicm9sZSI6ImNvcm9sbGFfZHJpdmVyIiwibmJmIjoxNTg1NDQyMDkyLCJleHAiOjE1ODU0NDM4OTIsImlhdCI6MTU4NTQ0MjA5Mn0.jcJBe4k3Q6XJBc4_LgGse1b_aSx3oT3NbMIAGq3wV18

# {
#     "Name": "Laptop"
# }

#DELETE http://localhost:5000/api/categories/1

#Good

# GET http://localhost:5000/api/goods
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ItCU0LzQuNGC0YDQuNC5Iiwicm9sZSI6ImxleHVzX2RyaXZlciIsIm5iZiI6MTU4Njk4NDk1MCwiZXhwIjoxNTg2OTg2NzUwLCJpYXQiOjE1ODY5ODQ5NTB9.Wmzr4OIQAHWa7R4xAq9S77wloNTpFAV9QRqjTlXZwu8

# POST http://localhost:5000/api/goods
# Content-Type: application/json

# {
#     "GoodName": "Acer Aspire ES1-411-C1XZ",
#     "GoodCount": 3,
#     "Price": 6399.00,
#     "CategoryId": 100
# }

# PUT http://localhost:5000/api/goods/1
# Content-Type: application/json

# {
#     "GoodName": "Acer Aspire ES1-411-C1XZ",
#     "GoodCount": 3,  
#     "Price": 8150.00,
#     "CategoryId": 100
# }

# DELETE http://localhost:5000/api/goods/1

#Authenticate

# POST http://localhost:5000/api/auth/authenticate
# Content-Type: application/json

# {
#     "Login": "Lexus",
#     "Password": "Lexus123"
# }

# GET http://localhost:5000/api/categories
#  Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ItCb0Y7QtNC80LjQu9CwIiwicm9sZSI6ImNvcm9sbGFfZHJpdmVyIiwibmJmIjoxNTg1NDQyMDkyLCJleHAiOjE1ODU0NDM4OTIsImlhdCI6MTU4NTQ0MjA5Mn0.jcJBe4k3Q6XJBc4_LgGse1b_aSx3oT3NbMIAGq3wV18

# #User

# GET http://localhost:5000/api/users
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ItCU0LzQuNGC0YDQuNC5Iiwicm9sZSI6ImxleHVzX2RyaXZlciIsIm5iZiI6MTU4NzEzNTgxOSwiZXhwIjoxNTg3MTM3NjE5LCJpYXQiOjE1ODcxMzU4MTl9.u2ZMTxrL3KXA1suX5QMQ4aS-aZSWcSlUAss8Z987-JE

PUT http://localhost:5000/api/users/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ItCU0LzQuNGC0YDQuNC5Iiwicm9sZSI6ImxleHVzX2RyaXZlciIsIm5iZiI6MTU4NzEzNTgxOSwiZXhwIjoxNTg3MTM3NjE5LCJpYXQiOjE1ODcxMzU4MTl9.u2ZMTxrL3KXA1suX5QMQ4aS-aZSWcSlUAss8Z987-JE

{
        "firstname": "qqqq",
        "lastname": "ww",
        "login": "eeee"
}

#Role

# GET http://localhost:5000/api/roles
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ItCU0LzQuNGC0YDQuNC5Iiwicm9sZSI6ImxleHVzX2RyaXZlciIsIm5iZiI6MTU4Njk2NzgzMiwiZXhwIjoxNTg2OTY5NjMyLCJpYXQiOjE1ODY5Njc4MzJ9.ur-pz1aNRBHbwFsoNUh6a7YTwQVyadp7dZRpqgk1dbw

PUT http://localhost:5000/api/roles/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ItCU0LzQuNGC0YDQuNC5Iiwicm9sZSI6ImxleHVzX2RyaXZlciIsIm5iZiI6MTU4Njk2NzgzMiwiZXhwIjoxNTg2OTY5NjMyLCJpYXQiOjE1ODY5Njc4MzJ9.ur-pz1aNRBHbwFsoNUh6a7YTwQVyadp7dZRpqgk1dbw
Content-Type: application/json

{
    "name": "ghj11"
}